<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    
    '(new)' => '(νέο)',
    '<h4>Operation Disallowed</h4><hr>Invalid request signature detected during tree data <b>{action}</b> action! Please refresh the page and retry.{params}' => '',
    'Active' => 'Ενεργό',
    'Add new' => 'Προσθήνη νέου',
    'Add new root' => 'Προσθήνη νέας ρίζας',
    'Admin Settings' => 'Ρυθμίσεις Διαχείρισης',
    'Already at bottom-most {node} in the hierarchy.' => 'Είστε ήδη στο τελευταίο {node} στην ιεραρχία.',
    'Already at left-most {node} in the hierarchy.' => 'Είστε ήδη στο πιο αριστερό {node} στην ιεραρχία.',
    'Already at right-most {node} in the hierarchy.' => 'Είστε ήδη στο πιο δεξιό {node} στην ιεραρχία.',
    'Already at top-most {node} in the hierarchy.' => 'Είστε ήδη στο πιο πάνω {node} στην ιεραρχία.',
    'Are you sure you want to remove this {node}?' => 'Είσαι σίγουρος πως θέλεις να διαγράψεις τον {node}?',
    'Cannot create {node}. Parent node is not saved or is invalid.' => 'Αδύνατη δημιουργία {node}. Κόμβος γονέα δεν είναι αποθηκευμένος ή μη έγκυρος.',
    'Cannot move root level {nodes} before or after other root level {nodes}.' => 'Αδύνατη μετακίνηση επιπέδου ρίζας {nodes} πριν ή μετά από άλλο επίπεδο ρίζας {nodes}.',
    'Cannot move this {node} as the {node} details are not saved yet.' => 'Αδύνατη μετακίνιση του {node} ως {node} λεπτομέρειες δεν έχουν αποθηκευτεί ακόμη.',
    'Child Allowed' => 'Παιδιά επιτρέπονται',
    'Clear search results' => 'Καθαρισμός αποτελεσμάτων αναγήτησης',
    'Collapsed' => 'Μάζεμα',
    'Default' => 'Εξ ορισμού',
    'Delete' => 'Διαγραφή',
    'Depth' => 'Βάθος',
    'Disabled' => 'Ανενεργό',
    'Error removing the {node}. Please try again later.' => 'Λάθος κατα την διαγραφή του {node}. Παρακαλώ δοκιμάστε αργότερα.',
    'Error while creating the {node}. Please try again later.' => 'Λάθος κατα την δημιουργία του {node}. Παρακαλώ δοκιμάστε αργότερα.',
    'Error while moving the {node}. Please try again later.' => 'Λάθος κατα την μετακίνηση του {node}. Παρακαλώ δοκιμάστε αργότερα.',
    'Error while removing the {node}. Please try again later.' => 'Λάθος κατα την διαγραφή του {node}. Παρακαλώ δοκιμάστε αργότερα.',
    'Error while saving the {node}. Please try again later.' => 'Λάθος κατα την αποθήκευση του {node}. Παρακαλώ δοκιμάστε αργότερα.',
    'Error while viewing the {node}. Please try again later.' => 'Λάθος κατα την προβολή του {node}. Παρακαλώ δοκιμάστε αργότερα.',
    'ID' => 'ID',
    'Icon' => 'Εικονίδιο',
    'Icon Type' => 'Τύπος Εικονιδίου',
    'Left' => 'Αριστερά',
    'Movable Down' => 'Μετακινήσιμο Κάτω',
    'Movable Left' => 'Μετακινήσιμο Αριστερά',
    'Movable Right' => 'Μετακινήσιμο Δεξιά',
    'Movable Up' => 'Μετακινήσιμο Πάνω',
    'Move Down' => 'Μετακινήση Κάτω',
    'Move Left' => 'Μετακινήση Αριστερά',
    'Move Right' => 'Μετακινήση Δεξιά',
    'Move Up' => 'Μετακινήση Πάνω',
    'Name' => 'Όνομα',
    'No valid {nodes} are available for display. Use toolbar buttons to add {nodes}.' => 'Μη έγκυροι {nodes} διαθέσιμοι για προβολή. Χρησιμοποίηση τα κουμπιά της γραμμή εργαλείων για να προσθέσεις {nodes}.',
    'Read Only' => 'Μόνο Ανάγνωση',
    'Refresh' => 'Ανανέωση',
    'Removable' => 'Διαγράψιμο',
    'Removable (with children)' => 'Διαγράψιμο (με παιδιά)',
    'Reset' => 'Επαναφορά',
    'Right' => 'Δεξιά',
    'Root' => 'Ρίζα',
    'Save' => 'Αποθήκευση',
    'Saved the {node} details successfully.' => 'Εποθήκευση στοιχείων {node} Επιτυχής.',
    'Search...' => 'Αναζήτηση...',
    'Select a {node} by clicking on one of the tree items.' => 'Επέλεξε ένα {node} κάνοντας κλικ σε ένα από τα στοιχεία του δένδρου.',
    'Select...' => 'Επιλογή...',
    'Selected' => 'Επιλεγμένο',
    'The selected {node} cannot be moved.' => 'Το επιλεγμένο {node} δεν μπορεί να μετακινηθεί.',
    'The untitled {node} was removed.' => 'Το Χωρίς Τιτλο  {node} διαγράφηκε.',
    'The {node} was moved successfully.' => 'Ο {node} μετακινήθηκε επιτυχώς.',
    'The {node} was removed successfully.' => 'Ο {node} διαγράφηκε επιτυχώς.',
    'The {node} was successfully created.' => 'Ο {node} was δημιουργήθηκε επιτυχώς.',
    'This operation is not allowed.' => 'Μη επιτρεπτή λειτουργία.',
    'Untitled' => 'Χωρίς Τίτλο',
    'Visible' => 'Ορατό',
    'You cannot add children under this {node}.' => 'Δεν μπορείς να προσθέσεις παιδιά κάτω από τον {node}.',
    'node' => 'Κόμβος',
    'nodes' => 'Κόμβοι',
    '{node} # {id} - \'{name}\': {error}' => '',
    'Categories' => 'Κατηγορίες',   
];
